# Site settings
title: Benjamin Yi
description: Benjamin Yi's Personal Website
baseurl: ''
url: 'https://bencyi.github.io'

# User settings
username: Benjamin Yi
user_description: user_Desc
user_title: Computer Science Senior @ University of Maryland, College Park
email: bencyi@me.com
twitter_username: benc_yi
github_username: bencyi
linkedin_username: benjamincyi
# Build settings
markdown: kramd own
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
    clippings: all
    comments: all
    endings: []
    profile: false

# Links to include in menu navigation
# For external links add external: true
links:
    - title: Home
      url: /
    - title: Courses
      url: /courses
    - title: Projects
      url: /projects
    - title: Misc
      url: /misc

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
