# Site settings
title: Ben's Portfolio
description: Benjamin Yi's Personal Website
baseurl: ''
url: 'https://bencyi.github.io'

# User settings
username: Benjamin Yi
user_description: user_Desc
user_title: Computer Science Senior @ University of Maryland
email: bencyi@Me.com
twitter_username: benc_yi
github_username: bencyi
gplus_username: gplus_user
disqus_username: disqus_user

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
    clippings: all
    comments: all
    endings: []
    profile: false

# Links to include in menu navigation
# For external links add external: true
links:
    - title: Home
      url: /
    - title: Series
      url: /series
    - title: Tags
      url: /tags
    - title: About Me
      url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
